name: example
description: Showcase App for Fluent UI package for Flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.4.1
  dio: ^4.0.6
  im_animations: ^0.1.2
  provider: ^6.0.3
  system_theme: ^2.0.0
  window_manager: ^0.2.7
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.5
  clipboard: ^0.1.3
  email_validator: ^2.0.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  flutter_markdown: ^0.6.10+5
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  dropdown_search: ^5.0.3
  open_file: ^3.2.1
  path_provider: ^2.0.6
  pdf: ^3.6.1
  responsive_ui: ^3.0.0
  fl_chart: ^0.55.2
  shared_preferences: ^2.0.16
  top_snackbar_flutter: ^3.0.0+1
  jwt_decode: ^0.3.1
  tab_container: ^2.0.0
  file_picker: ^4.6.1
  date_format: ^2.0.7
  barcode_widget: ^2.0.4
  printing: ^5.5.0
  image: ^3.0.2
  image_picker: ^0.8.4
  screenshot: ^1.2.2
  widgets_to_image: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
  
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts\Dosis-Bold.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts\BebasNeue-Regular.ttf
    - family: LaBelleAurore
      fonts:
        - asset: fonts\LaBelleAurore-Regular.ttf
    - family: Chakra
      fonts:
        - asset: fonts\ChakraPetch-SemiBold.ttf
    - family: JosefinSans
      fonts:
        - asset: fonts\JosefinSans-Medium.ttf
flutter_native_splash:
  color: "#42a5f5"
  image: web/assets/flutter_logo.png
